sensitive_words = [
"Paris sportifs", "Jeux d'argent", "Bookmaker", "Mise", "Cote", "Gain", "Paris en ligne", "Parieur", 
"Free bet", "Casino", "Roulette", "Poker", "Blackjack", "Machine à sous", "Loterie", "Grattage", 
"Paris mutuels", "Pari combiné", "Pari à handicap", "Cashout", "Live betting", "Pari live", "Cote dynamique", 
"Match fixing", "Addiction au jeu", "Jeu compulsif", "Stratégie de mise", "Bonus de bienvenue", 
"Promotion de paris", "Pari anonyme", "Enregistrer un compte", "Limites de mise", "Mise maximale", 
"Pari gratuit", "Bilan de gains", "Historique de paris", "Demande de retrait", "Inscription au casino", 
"Application de paris", "Statistiques sportives", "Événements sportifs", "Favori", "Outsider", 
"Performance des équipes", "Analyse des matchs", "Résultats en direct", "Paris sur le football", 
"Paris sur le basket", "Paris sur le tennis", "Pari sur les courses", "Horaires de matchs", 
"Rencontres sportives", "Compétition", "Tournois de poker", "Salle de poker en ligne", 
"Croupier en direct", "Tirage au sort", "Gains potentiels", "Risque de perte", 
"Contrôle de jeu", "Règlementation sur les jeux", "Dépendance au jeu", 
"Alerte de jeu", "Assistance aux joueurs", "Prévention des jeux d'argent", 
"Légalité des paris", "Sites de jeux fiables", "Cotes de victoire", 
"Paiement sécurisé", "Cash game", "Pari sportif sur mobile", "Surveillance des paris", 
"Limite de dépôt", "Pari anonyme", "Système de mise", "Arbitrage des paris", 
"Cote fixe", "Paris à long terme", "Équilibre des mises", "Stratégie de bankroll", 
"Bilan de pertes", "Éthique des jeux", "Réputation du bookmaker", "Mises sportives", 
"Stratégie de paris", "Paris en direct", "Tactiques de mise", "Récompenses de fidélité", 
"Compte de jeux", "Bilan de jeu", "Chiffre de paris", "Limites de temps de jeu", 
"Taux de retour", "Paris sur les événements", "En ligne", "Addiction aux casinos", 
"Lutte contre l'addiction", "Profil de joueur", "Vérification d'identité", "Conditions générales de pari",
"Sexe oral", 
"Alcool", "Drogue", "Addiction", "Dépendance", "Cocaïne", "Héroïne", "Meth", "Ecstasy", "Cannabis", 
"Marijuana", "Crack", "Hallucinogène", "Stupéfiant", "Drogues dures", "Drogues légères", "Tabac", 
"Sevrage", "Syndrome de sevrage", "Binge drinking", "Société de consommation", "Alcoolisme", 
"Intoxication", "Siroter", "Verre", "Shot", "Cocktail", "Mixologie", "Consommation", 
"Rituel de consommation", "Alerte d'alcool", "Drogue synthétique", "Drogue de synthèse", 
"Éthanol", "Acide", "LSD", "MDMA", "Substance contrôlée", "Usage récréatif", "Usage abusif", 
"Syndrome de dépendance", "Drogue illicite", "Paraphernalia", "Sels de bain", "Kratom", 
"Opioïdes", "Calme", "Anxiété", "Excitation", "État altéré", "Ébriété", "État d'ébriété", 
"Saouler", "Buzz", "Se saouler", "Bourré", "Fumer", "Inhaler", "Sniffer", "Clope", "Fumer du cannabis", 
"Vapotage", "E-cigarette", "E-liquide", "Vaporisateur", "Psychoactif", "État de transe", 
"Drogue de club", "Drogues de designer", "Faux médicaments", "Usage contrôlé", "Médicament sur ordonnance", 
"Addiction aux médicaments", "Comportement addictif", "Compulsion", "Recours aux drogues", "Drogues injectables", 
"Drogues orales", "Risque d'overdose", "Surdose", "Récupération", "Désintoxication", "Traitement de la dépendance", "Thérapie", "Groupes de soutien", "Récupération communautaire", "Éducation à la prévention", "Problèmes de santé", "Consequences", "Délit", "Crime lié à la drogue", "Parcours de réhabilitation", "Facteurs de risque", "Vulnérabilité", "Alerte d'overdose", "Prévention de l'addiction", "Soutien aux familles",
"Drogues dures", 
"Methamphetamine", 
"Héroïne", 
"Cocaïne", 
"Ecstasy", 
"Shotgun", 
"Pistolet", 
"Pornographique", 
"Nudité explicite", 
"Escorte", 
"Camgirl", 
"Webcam sex", 
"Vente de drogue", 
"Gangster", 
"Crime", 
"Cartel", 
"Violation", 
"Cruauté", 
"Sado maso", 
"Asphyxie érotique", 
"Sexe violent", 
"Violence sexuelle", 
"Drogues illégales", 
"Crack", 
"Bordel", 
"Striptease", 
"Tueur en série", 
"Trafic d’êtres humains", 
"Torture mentale", 
"Brutalité", 
"Assassin", 
"Extasy", 
"Délinquance juvénile", 
"Violence armée", 
"Comportement sexuel", 
"Trafic d'armes", 
"Attaque", 
"Cannibale", 
"Châtiment corporel", 
"Sexe non consenti", 
"Prédateur", 
"Violences sexuelles", 
"Inceste", 
"Exhibitionnisme", 
"Orgie", 
"Pédo criminalité", 
"Vente illégale", 
"Délit", 
"Abus sexuel", 
"Porn revenge", 
"Film X", 
"Sexe entre mineurs", 
"Diffusion de vidéos intimes", 
"Infraction", 
"Corruption de mineurs", 
"Tirs", "Hallucinogène", "Pédopornographie", "Trafic de stupéfiants", 
"Gang de rue", "Auto mutilation", "Sexe de groupe", "Snuff movie", "Domination", "Contrôle mental", 
"Enregistrement intime non consenti", "Tortionnaire", "Blanchiment d'argent", "Pornographie illégale", 
"BDSM", "Voyeurisme", "Traffic sexuel", "Déstabilisation mentale", "Revenge porn", "Trafic de mineurs", 
"Violence conjugale", "Meurtres en série", "Pornographie amateur", 
"Séquestrer", "Comportement coercitif", 
"Soumission sexuelle", "Trafic d’organes", "Drogues synthétiques", 
"Alcoolisme", "Violences domestiques", 
"Menace terroriste", "Cyber crime", "Kidnappeur", "Brutalisation", 
"Terroriste", "Menace armée", "Pédopornographie", 
"Pornographie extrême", "Vol à main armée", 
"Violences verbales", "Violence sadique", "Piège sexuel", "Débauche", "Sexe sans protection", 
"Maltraitance infantile", "Molestation", "Entraînement militaire clandestin", "Violent", 
"Drogue", "Pornographie", "Arme", "Meurtre", "Kidnapping", 
"Alcool", "Sexe", "Suicide", "Horreur", "Fusillade", 
"Terreur", "Explosion", "Abus", "Guerre", "Agression", "Trafiquant", "Pédophilie", 
"Dépression", "Cannabis", "Homicide", "Viol", 
"Esclavage", "Extorsion", "Gang", "Mafia", "Torture", "Évasion", "Overdose", "Tabac", "Violenté", 
"Harcèlement", "Trafic", "Sexe explicite", 
"Prostitution", "Profanation", "Incendie criminel", "Séquestration", "Cannibalisme", "Délinquance", 
"Radicalisme", "Terrorisme", "Assassin", 
"Fusil", "Fentanyl", "Strangulation", "Étranglement", "Sabotage", "Bombardement", "Génocide", 
"Sadisme", "Scandale sexuel", "Cyberharcèlement", 
"Fraude", "Crime organisé", "Racket", "Violence domestique", "Piratage", "Trafic humain", 
"Tortionnaire", "Nudité", "Contraband", "Brutal", "Chantage", 
"Pornographique", "Porno", "Armes blanches", "Escroquerie", "Manipulation", 
"Corruption", "Larcin", "Attentat", "Fanatisme", "Vengeance", "Décapitation", 
"Bombardier", "Criminalité", "Orgies", "Sadomasochisme", "Conspiration", 
"Violenté", "Oppression", "Sanglant", "Traque", "Pornographie enfantine", "Esclavagisme", 
"Coupable", "Combats illégaux", "Emprise", "Vandalisme", "Perversion", 
"Trafic de drogue", "Enlèvement", "Émeute", "Exorcisme", "Torturé", 
"Capture d'otage", "Sang", 
"Démembrement", "Porn addicted", "paris sportif"]